### ISSUE TITLE
Хардкод пути src при определении исходников вызывает проблемы при работе с исходниками в формате 1С

### ISSUE THREAD

**Issue by artbear** [bia-technologies/edt_ripper#1]
суть проблемы - есть репо в формате 1С, нужно собрать ошибки от ЕДТ и показать их в Сонаре

для этого идет конвертация исходников 1С в формат ЕДТ
далее запуск ЕДТ на анализ
затем должен подключиться едт-риппер и создать результаты для сонара

в итоге есть 2 каталога исходников
- 1й с исходниками ЕДТ, с ним работает анализ ЕДТ, vrunner edt-validate
- 2й с исходниками 1С, с ними должен поработать едт-риппер, чего не происходит, т.к. нет сопоставления проекта из ЕДТ с исходниками из 1С

https://github.com/bia-technologies/edt_ripper/blob/master/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9F%D0%B0%D1%80%D1%81%D0%B5%D1%80%D0%9E%D1%88%D0%B8%D0%B1%D0%BE%D0%BA.os#L151

а не всегда путь src валидный.
например, согласно шаблону Vanessa-bootstrap внутри src есть подкаталоги cf, cfe и другие

хорошо бы явно указывать нужные подкаталоги, а не хардкодить src

**Comment by artbear** [comment]
В итоге ошибка
```
ОТЛАДКА - [o.app.edt-ripper] - Использован путь проекта .\back\src
ОТЛАДКА - [oscript.app.cf_info] - Это выгрузка конфигурации: Нет
ОТЛАДКА - [oscript.app.cf_info] - Это выгрузка EDT: Нет
КРИТИЧНАЯОШИБКА - [o.app.edt-ripper] - {Модуль C:\Users\aayukhanov\AppData\Local\ovm\current\lib\v8metadata-reader\src\Классы\Путь1СПоМетаданным.os / Ошибка в строке: 130 / Не удалось определить тип выгрузки}
```

**Comment by artbear** [comment]
при указаннии "правиильного полного" птуи ошибка пропадает
видно по `Это выгрузка конфигурации: Да`
```
ОТЛАДКА - [o.app.edt-ripper] - Использован путь проекта .\back/src/cf
ОТЛАДКА - [oscript.app.cf_info] - Это выгрузка конфигурации: Да 
ОТЛАДКА - [oscript.app.cf_info] - Это выгрузка EDT: Нет
```

**Comment by artbear** [comment]
Посмотрел код, попробовал позапускать.
Есть проблема
- для исходников в формате ЕДТ хардкод `src` вполне валиден
- проблема с исходниками в формате 1С

в этом случае 
1 нужно помнить, что может быть несколько проектов
2 нужно иметь возможность указать как имя проекта в ЕДТ, так и путь этого проекта в исходниках 1С
например, если в одном репо и расширение и конфигурация, то пути будут разные src\cfe и src\cfe

3 просто так массив в доп.опцию не передашь

непонятно, как реализовать

**Comment by theshadowco** [comment]
массив через `;`

**Comment by artbear** [comment]
описание проблемы - есть репо в формате 1С, нужно собрать ошибки от ЕДТ и показать их в Сонаре

для этого идет конвертация исходников 1С в формат ЕДТ
далее запуск ЕДТ на анализ
затем должен подключиться едт-риппер и создать результаты для сонара

в итоге есть 2 каталога исходников
- 1й с исходниками ЕДТ, с ним работает анализ ЕДТ, vrunner edt-validate
- 2й с исходниками 1С, с ними должен поработать едт-риппер, чего не происходит, т.к. нет сопоставления проекта из ЕДТ с исходниками из 1С

**Comment by IT-Medved** [comment]
Привет, спасибо за хорошее замечание.
Харкод 'src' действительно стоит убрать, не у всех проекты так расположены.
1. У нас уже есть структура параметров которая может помочь нам с этим ишузом. И самый простой вариант кмк надо научить аргумент PROJECTS понимать более сложные пути. Это уже массив строк.
Сейчас мы туда передаем корневые каталоги с проектами чтобы потом сделать несколько вещей.
` ./my_awesome_rep/ configuration exts `

 -  построить пути вида  ` my_awesome_rep/configuration/src ` ` my_awesome_rep/exts/src `
 - Смапить имя проекта из выхлопа ЕДТ и путь чтобы понимать к чему соотносить замечания. ( хранить генераторы путей)

Если мы сделаем аргумент PROJECTS чуть более умным и уберем автодобавление `src` в путь ,  он сможет принимать полные относительные пути напр.
` ./my_awesome_rep/ configuration/src exts/ext1/src exts/ext2/src ` - ЕДТ
` ./my_awesome_rep/ src/conf src/epf src/erf  src/cfe`  - 1C 

Для построения путей это будет работать из коробки, для паминга замечаний имя проекта в выводе ЕДТ  можно доработать и вычленять имя проекта отбасывая последнюю часть `/src` если она есть и брать окончание пути

**Comment by artbear** [comment]
@jmpjck тут проблема в том, что в варианте с исходниками 1С нужно сопоставление имени проекта ЕДТ и исходника из 1С-папки

как в предлагаемом варианте его указать?
-  `./my_awesome_rep/ src/conf src/epf src/erf  src/cfe` - 1C

например, имя проекта у меня backend, а относительный путь в исходниках 1С - back/src/cf
