### ISSUE TITLE
Выдаются ненужные предупреждения, если у формы или объекта конфигурации нет соответствующего модуля

### ISSUE THREAD

**Issue by artbear** [bia-technologies/edt_ripper#2]
Например, если в исходном файле замечания от ЕДТ написано `РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма`
тогда будет ненужный и отвлекающий лог из используемой библиотеки v8metadata-reader (файл Путь1СПоМетаданным)
```
ПРЕДУПРЕЖДЕНИЕ - [oscript.app.cf_info] - Не поддерживаемый объект РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма.МодульОбъекта
ПРЕДУПРЕЖДЕНИЕ - [oscript.app.cf_info] - Не поддерживаемый объект РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма.МодульМенеджера
ПРЕДУПРЕЖДЕНИЕ - [oscript.app.cf_info] - Не поддерживаемый объект РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма.МодульНабораЗаписей
ПРЕДУПРЕЖДЕНИЕ - [oscript.app.cf_info] - Не поддерживаемый объект РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма.МодульКоманды
ПРЕДУПРЕЖДЕНИЕ - [oscript.app.cf_info] - Не поддерживаемый объект РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма.МодульМенеджераЗначения
```

Проблема в том, что метод Конфигурация.ПодобратьМодуль пытается найти модуль, что неверно, т.к. нет модуля нет вообще

**Comment by artbear** [comment]
Пример ошибки от ЕДТ
```
2023-01-22T15:05:28+0300	Значительная	Ошибка конфигурации	
backend	com.e1c.dt.check.form:form-data-path	
РегистрСведений.ОбъектыПоФильтрам.Форма.ФормаСписка.Форма		
Свойство "Путь к данным" имеет некорректное значение "Список.Продукт": 
2 сегмент "Продукт" ссылается на неизвестный объект
```

**Comment by artbear** [comment]
Обработка самого замечания проходит корректно, но Предупреждения в логе значительно отвлекают.
их немало

**Comment by IT-Medved** [comment]
Привет, спасибо за поднятую проблему =) 
Тут палка о 2 концах что называется. Можно сделать поиск модуля умнее и определять что это за объект и следом проверять его на модуль. Но, если такового не будет, ты все равно получишь такое же сообщение. Профит в том, что их будет меньше.
Но усложнится логика + не уйдет проблема.
Есть идея - подавлять( управлять) предупреждениями которые порождаются  в библиотеке v8metadata-reader. ( или любой библиотечной зависимости.
1. Я хочу копнуть в сторону logos и посмотреть могу ли я там настраивать уровни так, чтобы предупреждения не выводились, или выводились только из основного лога приложения.
2. Если не получится посмотрю в сторону вывода в отладочный файл а потом чтения сообщений из него по маске.
3. Если все еще не будет хорошего варианта приду с изменениями в v8metadata-reader

**Comment by IT-Medved** [comment]
Первый вариант сработал, фикс будет
